# Generated by Django 4.0.6 on 2022-10-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base', models.TextField()),
                ('avatar', models.ImageField(upload_to='images/instructors', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструктора',
                'db_table': 'instructor',
            },
        ),
    ]
